### ISSUE TITLE
Module '"firebase-functions"' has no exported member 'crashlytics'.

### ISSUE THREAD

**Issue by skhaz** [firebase/firebase-functions-test#104]
> build
> tsc

node_modules/firebase-functions-test/lib/providers/crashlytics.d.ts:1:10 - error TS2305: Module '"firebase-functions"' has no exported member 'crashlytics'.

1 import { crashlytics } from 'firebase-functions';
           ~~~~~~~~~~~


Found 1 error.

**Comment by VeryCrazyDog** [comment]
@skhaz Have you check #97?

**Comment by skhaz** [comment]
@VeryCrazyDog #97 worked flawlessly
