### ISSUE TITLE
Can't access a non-default database.

### ISSUE THREAD

**Issue by cairinmichie** [firebase/firebase-functions-test#12]
### Version info

**firebase-functions-test:** ^0.1.1

**firebase-functions:** ^1.0.1

**firebase-admin:** ^5.12.0

### Test case

Setting up the test object to connect to a non-default database in a project:
```
const test = require('firebase-functions-test')({
  databaseURL: 'https://non-default-db.firebaseio.com/',
  projectId: 'my-project'
}, './service-account-key.json')
```

Then creating a snapshot causes the snapshot to be created in the default database (I just used the example code here):
```const snap = test.database.makeDataSnapshot('input', 'messages/11111/original')```

### Steps to reproduce

Follow the [guide](https://firebase.google.com/docs/functions/unit-testing), for online mode, but replacing the default database url with that of another database as shown above.

### Expected behavior

The snap should be created in the specified database and not the default one.

### Actual behavior

The snap is created in the default database.

**Comment by laurenzlong** [comment]
That is a bug, thanks for reporting! I'll look into it.

**Comment by cairinmichie** [comment]
Any update on this?

**Comment by mikeb-celtx** [comment]
This actually works for me with 0.1.2

**Comment by abehaskins** [comment]
Just tested this and can confirm that it also works for me (switching databases in the same project). Feel free to re-open if you're still experiencing this.
