### ISSUE TITLE
Impossible to test wrapped functions with App check

### ISSUE THREAD

**Issue by LeMimit** [firebase/firebase-functions-test#122]
### Version info

**firebase-functions-test:** `0.3.2`

**firebase-functions:** `3.15.5`

**firebase-admin:** `9.11.1`

### Test case

I would like to test a callable function which check if there is an `app` context because App check is activated on my project.

The following function is called at the beginning of the callable function:

```typescript
export function verifyAppCheck(context: functions.https.CallableContext) : void {
  if (context.app == undefined) {
    throw new functions.https.HttpsError("unauthenticated", "Unauthorized Access");
  }
}
```

For now it is impossible to test my function because the `wrap` function from `firebase-functions-test` do the following call 
```typescript
if (isCallableFunction) {
  _checkOptionValidity(['auth', 'instanceIdToken', 'rawRequest'], options);
  let callableContextOptions = options;
  context = Object.assign({}, callableContextOptions);
}
```

It is impossble to specify an `app` object.

### Steps to reproduce

- Create a Callable function which check if `context.app` is defined
- Try to pass an `app` object while calling a wrapped function
- Get the the error `Options object {"auth":{"uid":""},"app":{}} has invalid key "app"`

### Expected behavior

Be able to specify a fake `app` object to test a callable function when using App check.

### Actual behavior

Get an error while trying to specify a fake `app` object.

**Comment by taeold** [comment]
@LeMimit Thanks for the report. Yes, it looks like wrap function is incompatible with AppCheck integration we've introduced. We will fix this in the next release.

**Comment by LeMimit** [comment]
@taeold Thanks for your answer. Looking forward the next release then !

**Comment by fiveable-jferg** [comment]
Is there any sort of ETA for when this might be fixed?  It's kind of got me blocked on some things.  :-(

**Comment by taeold** [comment]
Sorry for the delays folks. I will try to get the new release by end of week.
