### ISSUE TITLE
Error: Unexpected error while acquiring application default credentials: Could not load the default credentials

### ISSUE THREAD

**Issue by dauledk** [firebase/firebase-functions-test#13]
### Intro
First I would like to thank you for this repo. At our team I have the responsibility of testing our firebase functions, and I feel that this repo will help with that. Awesome work 🔥 
I am trying to write a very simple test of a firebase helper function in typescript. I have cloned the sample functions project to make it easy to understand. I am trying to use firebase functions test in online mode, and connect to a test repo. I have also experimented with offline mode, but that requires a lot of stubbing as far as I understand, that I currently don't have that much experience with. Please let me know if you need more info :) 

### Version info

**firebase-functions-test:**
0.1.1
**firebase-functions:**
1.0.0
**firebase-admin:**
5.12.0
### Test case

Provide a minimal, complete, and verifiable example:
https://github.com/dauledk/functions-samples

### Steps to reproduce (now easier with the help of docker)

1. install docker (if you don't already have it installed)
2. run git clone https://github.com/dauledk/functions-samples.git
3. run npm run -s issue-13

### Expected behavior
That the function `src/helper-functions/read-users.ts` reads from firestore

### Actual behavior
I get this error like 15 times, and _nothing_ is read from firestore. 

```
(node:84300) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 15): Error: Unexpected error while acquiring application default credentials: Could not load the default credentials. Browse to https://developers.google.com/accounts/docs/application-default-credentials for more information.
```

Here is an abstract of the github repo: 

**src/helper-functions/read-users.ts** - small helper function that uses firebase-admin to read from firestore
```
import { firestore } from '../firebase';
export async function readUsersFromFirestore(): Promise<any[]> {
    try {
        const usersRef = firestore.collection('users');
        const snapshot = await usersRef.get();
        const users = snapshot.docs.map(doc => doc.data());
        return users; 
    } catch (error) {
        throw error;
    }
}
```
**src/firebase.ts** - small helper file, that calls initializeApp() on firebase-admin
```
import * as admin from 'firebase-admin'
console.log('firebase admin is now calling initializeApp()');
admin.initializeApp();

const firestore = admin.firestore();

export { firestore };
```

**test/index.spec.ts** - The test file
```
import { join } from 'path';

const test = require('firebase-functions-test')({
    databaseURL: 'https://eddystone-test-e4cd3.firebaseio.com',
    storageBucket: 'eddystone-test-e4cd3.appspot.com',
    projectId: 'eddystone-test-e4cd3',
}, join(__dirname, `./eddystone-test.json`));

import { expect, assert } from 'chai';

describe('Cloud Functions', () => {
    let readUsers;
    
    before(async () => {
        readUsers = await import('../src/helper-functions/read-users');
    });

    it('Testing read users', async () => {
        try {
            console.log('Now testing: read users');
            const result = await readUsers.readUsersFromFirestore();
            console.log(result);
        } catch (err) {
            console.log(`Testing read users failed with: '${err.message}'`);
        }
    });    
});
```

**Comment by laurenzlong** [comment]
This is most likely caused by issues with the service account key. Please ensure that you only create a service account key from the App Engine default service account (not any other account that you create), and that the service account has "editor" permission. (You can check for that in [this link](https://console.cloud.google.com/iam-admin/iam))

**Comment by dauledk** [comment]
I was not using the App Enginge default service account. However I have no created a key here: 
<img width="1667" alt="screen shot 2018-04-21 at 09 29 50" src="https://user-images.githubusercontent.com/9967422/39081774-a8071cb8-4547-11e8-817d-7a6fd7e5010a.png">
And checked the editor permission here as suggested: 
<img width="1263" alt="screen shot 2018-04-21 at 09 34 49" src="https://user-images.githubusercontent.com/9967422/39081777-b0afb820-4547-11e8-8d29-805d790aa02f.png">
But I still get the error: 

```
Error: Unexpected error while acquiring application default credentials: Could not load the default credentials.
Browse to https://developers.google.com/accounts/docs/application-default-credentials for more information.
```
@GeneticSYS 
Thanks for the support.
According to [this](https://firebase.google.com/docs/functions/unit-testing) documentation, you should only stub `admin. initializeApp()` if you are in offline mode. My goal is to first get it working in online mode, and then see if I can make it offline afterwards.

**Comment by laurenzlong** [comment]
Thanks for sharing, could you try to print out `process.env.GOOGLE_APPLICATION_CREDENTIALS` after initializing `firebase-functions-test`, (perhaps before the line `readUsers = await import('../src/helper-functions/read-users');`)? It should print out the path to your key file.

**Comment by laurenzlong** [comment]
As well, just to rule out read permission issues. Can you modify the permissions on that file to be readable by all?

**Comment by dauledk** [comment]
I found new info - maybe it can help to solve the problem. I have this idea, that maybe we can debug the issue by looking at the following file?

**node_modules/google-gax/lib/grpcs.js**
```
/**
 * Creates a gRPC credentials. It asks the auth data if necessary.
 * @private
 * @param {Object} opts - options values for configuring credentials.
 * @param {Object=} opts.sslCreds - when specified, this is used instead
 *   of default channel credentials.
 * @return {Promise} The promise which will be resolved to the gRPC credential.
 */
GrpcClient.prototype._getCredentials = function _getCredentials(opts) {
  var PromiseCtor = this.promise;
  if (opts.sslCreds) {
    return PromiseCtor.resolve(opts.sslCreds);
  }
  var grpc = this.grpc;
  var getAuthClient = this.auth.getAuthClient.bind(this.auth);
  var sslCreds = grpc.credentials.createSsl();
  return new PromiseCtor(function(resolve, reject) {
    getAuthClient(function(err, auth) {
      if (err) {
        reject(err);
      } else {
        var credentials = grpc.credentials.combineChannelCredentials(
          sslCreds,
          grpc.credentials.createFromGoogleCredential(auth)
        );
        resolve(credentials);
      }
    });
  });
};
```
I added a `console.log(opts)` at line 115 of the file. Gave me the following: 
```
{ servicePath: 'firestore.googleapis.com',
  port: 443,
  clientConfig: {},
  projectId: '<project id>', <-- the correct Project ID
  libName: 'gccl',
  libVersion: '0.13.1' }
```
Does that help or?

**Comment by dauledk** [comment]
Let me know if I can provide / try anything else for debugging. Can’t wait for this to get up and running :)

**Comment by laurenzlong** [comment]
@dauledk I copied and pasted your readUsersFromFirestore as well as your test function, and tried it out with one of my projects and its service account. I was able to get the test to pass and the contents stored in the "users" collection in Firestore to get printed. See screenshot attached. 
![screenshot from 2018-04-24 16-22-21](https://user-images.githubusercontent.com/3990804/39218870-baa6bc2a-47db-11e8-9373-2ebf77a67c10.png)

I'm going to close this issue as not reproducible. Sorry I can't help you any further. Some things that may be worth trying are:
- Use another project
- If you only need these test to run on your machine, and not any others, you can get rid of the second parameter when initializing 'firebase-functions-test'. Then use the firebase CLI to run "firebase functions:shell" at least once. This will write a credential to the ~/.config directory of your local machine. Which will also get picked up when you run tests written with firebase-functions-test. Again, this solution will NOT work if you need to run your tests in another machine or in a CI environment.

**Comment by dauledk** [comment]
Hi @laurenzlong. Thanks for taking your time to help. I understand that you close the issue, because you could not reproduce. I would probably have done the same. I however need the project to work with CI - so to continue from here I have done the following:

1. Created a free firebase project, only for this project
2. Exported the key and included it in the repo
3. Created a docker container. 

This means that the issue is now a lot easier to reproduce. 

1. Install docker (if you don't already have it installed)
2. run `git clone https://github.com/dauledk/functions-samples.git`
3. run `npm run -s issue-13`

And thats it :) Should reproduce the error. If you can confirm this, I hope you will reopen the issue. I would also like very much to help resolving the issue, but would probably need some guidance 😀

**Comment by laurenzlong** [comment]
Thanks for your persistence. There is actually a bug it turned out. Can you try this branch? https://github.com/firebase/firebase-functions-test/pull/15

**Comment by dauledk** [comment]
No worries - I'm glad you could reproduce after all the effort :) Can I install like ? `npm i --save firebase-functions-test@https://github.com/firebase/firebase-functions-test#ll-fixinitcleanup`, or have do I try out the branch?

**Comment by laurenzlong** [comment]
You should be able to run:

npm i https://github.com/firebase/firebase-functions-test#ll-fixinitcleanup

**Comment by dauledk** [comment]
Hi @laurenzlong - I noticed that you created a new branch. Tried installing with: 
```
npm i https://github.com/firebase/firebase-functions-test#laurenzlong-patch-1
```
Gives me the following package.json
```
"dependencies": {
    "chai": "^4.1.2",
    "firebase-admin": "^5.12.0",
    "firebase-functions": "^1.0.2",
    "firebase-functions-test": "git+https://github.com/firebase/firebase-functions-test.git#laurenzlong-patch-1",
    "sinon": "^4.5.0"
  },
```
When I try to do `npm test`, it however gives me the error: 
```
module.js:540
    throw err;
    ^

Error: Cannot find module 'firebase-functions-test'
    at Function.Module._resolveFilename (module.js:538:15)
    at Function.Module._load (module.js:468:25)
    at Module.require (module.js:587:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/alexbjorlig/Documents/firebase-issues/acquire-test-bug/functions-samples/typescript-getting-started/functions/test/index.spec.js:13:14)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
    at Module.require (module.js:587:17)
    at require (internal/module.js:11:18)
    at /Users/alexbjorlig/Documents/firebase-issues/acquire-test-bug/functions-samples/typescript-getting-started/functions/node_modules/mocha/lib/mocha.js:253:27
    at Array.forEach (<anonymous>)
    at Mocha.loadFiles (/Users/alexbjorlig/Documents/firebase-issues/acquire-test-bug/functions-samples/typescript-getting-started/functions/node_modules/mocha/lib/mocha.js:250:14)
    at Mocha.run (/Users/alexbjorlig/Documents/firebase-issues/acquire-test-bug/functions-samples/typescript-getting-started/functions/node_modules/mocha/lib/mocha.js:577:10)
    at Object.<anonymous> (/Users/alexbjorlig/Documents/firebase-issues/acquire-test-bug/functions-samples/typescript-getting-started/functions/node_modules/mocha/bin/_mocha:591:18)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
    at Function.Module.runMain (module.js:684:10)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3
```

**Comment by laurenzlong** [comment]
It is now released as v0.1.2, so you can now simply update by running:

npm i --save-dev firebase-functions-test

**Comment by dauledk** [comment]
Simply amazing. Updating to v0.1.2 fixes the problem. Great work - and thanks for taking your time to fix it. Now its time for some testing here in Copenhagen, local time 8 pm 🎉 😅

**Comment by laurenzlong** [comment]
You're welcome! Thanks for reporting.

**Comment by natew** [comment]
If you're here from google, this frustrated me all day and ended up being something very weird... Typescript.

We had a tsconfig like this:

```json
{
  "compilerOptions": {
    "strict": true,
    "skipLibCheck": true,
    // "incremental": true,
    "declaration": true,
    "declarationMap": true,
    "module": "CommonJS",
    "removeComments": true,
    "moduleResolution": "node",
    "esModuleInterop": true,
    "allowSyntheticDefaultImports": true,
    "target": "es2018",
    "noImplicitAny": false,
    "noUnusedLocals": true,
    "noUnusedParameters": true,
    "noEmitOnError": false,
    "strictNullChecks": false,
    "strictFunctionTypes": true,
    "preserveConstEnums": true,
    "experimentalDecorators": true,
    "emitDecoratorMetadata": true,
    "jsx": "react",
    "allowJs": false,
    "sourceMap": true,
    "resolveJsonModule": true,
    "lib": ["es2017", "es2018", "dom", "esnext.array"]
  },
  "exclude": ["**/*.test.ts", "**/*.test.tsx"],
  "typeAcquisition": {
    "enable": true
  }
}
```

and an extends config:

```json
{
  "extends": "../../tsconfig.base",
  "compilerOptions": {
    "composite": true,
    "module": "CommonJS",
    "target": "es2017",
    "outDir": "_",
    "rootDir": "src"
  },
  "include": ["src/**/*"],
  "references": []
}
```

The compiled output would look like this:

```js
"use strict";
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
var __importStar = (this && this.__importStar) || function (mod) {
    if (mod && mod.__esModule) return mod;
    var result = {};
    if (mod != null) for (var k in mod) if (Object.hasOwnProperty.call(mod, k)) result[k] = mod[k];
    result["default"] = mod;
    return result;
};
Object.defineProperty(exports, "__esModule", { value: true });
const express_1 = __importDefault(require("express"));
const firebase_admin_1 = __importDefault(require("firebase-admin"));
const functions = __importStar(require("firebase-functions"));
console.log('test', process.env.FIREBASE_CONFIG);
const serviceAccount = require('../app_data/serviceAccount.json');
firebase_admin_1.default.initializeApp({
    credential: firebase_admin_1.default.credential.cert(serviceAccount),
    databaseURL: 'https://orbit-3b7f1.firebaseio.com',
});
const app = express_1.default();
app.get('/index', async (_, res) => {
    const db = firebase_admin_1.default.firestore();
    const docRef = db.collection('apps').doc('123');
    await docRef.get();
    res.send({ ok: 'hi' });
});
exports.search = functions.https.onRequest(app);
//# sourceMappingURL=test.js.map
```

And you'd get this error + it would import the main file multiple times on requests. I believe something to do with syntheticDefaultImport, though not positive.
