### ISSUE TITLE
Invalid field "authType" for an https callable function

### ISSUE THREAD

**Issue by phcoliveira** [firebase/firebase-functions-test#162]
https://github.com/firebase/firebase-functions-test/blob/9f401ca71cc27cf766cc6e1e45e089e348c610d5/src/v1.ts#L221

Hello there. I think I found a bug, but it seems to be a mismatch between what is shown by the typing of the `wrapped` function.

```
    const wrapped = testFunctions.wrap(addPlayer)

    const result = await wrapped(data, {authType: 'USER', auth: {uid: 'p2'}})
```

Here is what I have. The type of the function `wrapped` suggests that the field `authType` is valid. However, while debugging a silent error, I found out that this field is not present in the array `validFields`.

![image](https://user-images.githubusercontent.com/594605/184510719-1132e5c3-a68d-4fa0-aa95-49ecac734aa9.png)

**Comment by TheIronDev** [comment]
Hi @phcoliveira ,

Apologies for the delay!!!

I'm chasing this down right now.

What type of function is `addPlayer`? (Is there a github link?)

I ask because it looks like `CallableFunctions` allow for a subset of options compared to non-callable functions.

[Callable Options](https://github.com/firebase/firebase-functions-test/blob/9f401ca71cc27cf766cc6e1e45e089e348c610d5/src/v1.ts#L160) vs (Non-Callable option list)[https://github.com/firebase/firebase-functions-test/blob/9f401ca71cc27cf766cc6e1e45e089e348c610d5/src/v1.ts#L169]

Thank you for your patience!!

Tyler

**Comment by phcoliveira** [comment]
Hello @TheIronDev, thank you for catching this up.

`addPlayer` is a callable function, I will write it down bellow.

I can understand that a callable function only accepts a subset of a request function. Perhaps it is only possible to determine this at runtime. But I do believe it is possible to determine the right set of options based on a conditional typing at compile time.

In case you need the function `addPlayer`, here it is:

```
/* eslint-disable import/no-unresolved */
import type {
  AddPlayer,
  Party,
  ServerUpdate,
} from '@all-aboard/firebase-js-sdk/party'
import {serverTimestamp} from '@firebase/database'
import {getApp} from 'firebase-admin/app'
import {getAuth} from 'firebase-admin/auth'
import {getDatabase} from 'firebase-admin/database'
import * as functions from 'firebase-functions'

export const addPlayer = functions.https.onCall(
  async (data: AddPlayer, context): Promise<void> => {
    const playerUid = context.auth?.uid

    if (!playerUid) {
      throw new functions.https.HttpsError(
        'unauthenticated',
        'Must be authenticated'
      )
    }

    const {key: partyKey, password} = data

    if (!partyKey || !password) {
      throw new functions.https.HttpsError(
        'invalid-argument',
        'Must pass a partyKey and password'
      )
    }

    const serverApp = getApp('server')
    const database = getDatabase(serverApp)
    const partyRef = database.ref(`/parties/${partyKey}`)
    const partySnap = await partyRef.once('value')

    if (!partySnap.exists()) {
      throw new functions.https.HttpsError('not-found', 'Resource not found')
    }

    const partyVal = partySnap.val() as Party
    const {password: serverPassword, playerUids} = partyVal
    const isAdmin = !playerUids // The first player must be the admin

    if (serverPassword !== password) {
      throw new functions.https.HttpsError(
        'permission-denied',
        'Wrong password'
      )
    }

    const update: ServerUpdate = {
      playerUids: {
        ...playerUids,
        [playerUid]: isAdmin,
      },
      updatedAt: serverTimestamp(),
    }

    await partyRef.update(update)
    const auth = getAuth(serverApp)
    await auth.setCustomUserClaims(playerUid, {partyKey, isAdmin})
  }
)
```

**Comment by TheIronDev** [comment]
I took an initial stab at splitting the return function apart, but I was only able to get that error thrown during runtime. Which doesn't compile time isn't doable... it just means I haven't gotten it yet. 🤷 

I'm happy to review any PRs that does get a compile-time check working though! 😄

**Comment by phcoliveira** [comment]
I will try to provide a PR for this. In case I am unable to do it, I will let you know.

**Comment by TheIronDev** [comment]
Thank you!! I'll review when it pops up ASAP!

**Comment by phcoliveira** [comment]
@TheIronDev, I couldn't figure out a way to do it.

I tried to do a conditional type for the wrapped function's second argument `options`. And I also tried using function overload, like this:

```
export function wrapV1<T>(
  cloudFunction: HttpsFunction & Runnable<T>
): WrappedFunction<T>;
export function wrapV1<T>(
  cloudFunction: CloudFunction<T>
): WrappedScheduledFunction | WrappedFunction<T> {
  ...
}
```

If it is possible to fix this with a reasonable amount of work, I am afraid I don't know how to do it.

**Comment by phcoliveira** [comment]
@TheIronDev, I made it work, but I can not say if it is pertinent or even acceptable.

I will push the changes to my fork, but I want to leave some pictures here to show you that it works.

![image](https://user-images.githubusercontent.com/594605/187706792-cce279e0-d8d5-4d36-92e7-bebde12ab6af.png)

![image](https://user-images.githubusercontent.com/594605/187706896-d15aa450-26dc-42c3-8445-69224ce43b16.png)

So, with my changes, TypeScript is smart enough to decide which options to pick based on the function passed to be wrapped.

**Comment by phcoliveira** [comment]
For the moment, I am confused because of two conflicting facts.

The first one is this error thrown when trying to wrap an `https.onRequest()` function.
https://github.com/firebase/firebase-functions-test/blob/9f401ca71cc27cf766cc6e1e45e089e348c610d5/src/v1.ts#L140

To corroborate this first fact, the test example does not wrap the `simpleHttp` function, as shown here:
https://github.com/firebase/quickstart-testing/blob/master/unit-test-cloud-functions/functions/test/functions.spec.js#L22

The second fact is a test which currently have a typing error. Such test actually wraps an `https.onRequest()` function, even though it should not be possible. So I might be missing something
https://github.com/phcoliveira/firebase-functions-test/blob/49e265ee7aad06becf2c66f5cda7275639a37e93/spec/providers/https.spec.ts#L73 

In any case, here is the PR:
https://github.com/firebase/firebase-functions-test/pull/166

**Comment by phcoliveira** [comment]
I guess I will have to provide another overload for `wrap` in this file for solving that type error:
https://github.com/phcoliveira/firebase-functions-test/blob/1c79ea65a87293e649c06653af32128e8d099b45/src/main.ts#L48

But please let me know what you think.

**Comment by phcoliveira** [comment]
@TheIronDev, I provided another signature for the wrap function and everything works now.
Please check it out.

https://github.com/firebase/firebase-functions-test/pull/166/files
