### ISSUE TITLE
Set "bucket" automatically from storageBucket

### ISSUE THREAD

**Issue by deremer** [firebase/firebase-functions-test#19]
When unit testing cloud storage triggered functions that need to download and manipulate the file (e.g., to create thumbnails), we need to use `storage.makeObjectMetadata()` to define a test image file to use. And, in order to make it work, we have to re-define our project "bucket" _in every test_ like this:

```
FbTest.storage.makeObjectMetadata({
      name: 'unit_tests/Amaze.png',
      bucket: 'my-firebase-project-id.appspot.com',
      contentType: 'image/png'
});
```

Since, we already define the storageBucket when [initializing the test library](https://firebase.google.com/docs/functions/unit-testing#initializing), it'd be preferred if the default value for "bucket" was automatically set. This would not only mean less code in tests, but also less opportunity for errors and confusion for people getting started with tests (it actually took me a bit of time to figure out what to do with "bucket" and "name", especially since all my images are in folders).

In fact, since Firebase projects only have one bucket, I don't know why a fb function unit test would ever need to specify one.

**Comment by abehaskins** [comment]
Seems like a reasonable request. Will put in a PR.

**Comment by deremer** [comment]
Thanks @abehaskins 

Also, to readers from the future, I'd like to amend my previous comment about Firebase projects only having one bucket. It's true there is a default bucket, but it's possible to have and access other storage buckets on GCP via firebase sdks: https://firebase.google.com/docs/storage/admin/start#use_custom_buckets
