### ISSUE TITLE
Firestore Timestamp Warning Doesn't Go Away

### ISSUE THREAD

**Issue by wujekbogdan** [firebase/firebase-functions-test#22]
### Version info

**firebase-functions-test:** ^0.1.3

**firebase-functions:** ^2.0.3

**firebase-admin:** ^6.0.0

### Test case

``` ts
import * as FunctionsTest from "firebase-functions-test";
import "jest";
import * as path from "path";
import config from "../src/config";
import * as functions from "../src/index";

describe("test", () => {

  let functionsTest;

  beforeAll(() => {
    const configPath = path.resolve(__dirname, `../../env/serviceAccountKey.test.json`);

    functionsTest = FunctionsTest({
      databaseURL: config("DATABASE_URL"),
      projectId: config("PROJECT_ID"),
    }, configPath);
  });

  it("should do something...", () => {
    const snap = functionsTest.firestore.makeDocumentSnapshot({
      test: 2,
    }, "test-test/test");

    const wrapped = functionsTest.wrap(functions.setDashbordEntryTimestampOnCreate);

    wrapped(snap).then(() => {
      // Do something
    });
  });

});
```

### Steps to reproduce

Just run the test.

### Expected behavior

The documentation should explain how to set `timestampsInSnapshots: true` when running unit tests.

### Actual behavior

I'm getting the following error in the console:

      The behavior for Date objects stored in Firestore is going to change
      AND YOUR APP MAY BREAK.
      To hide this warning and ensure your app does not break, you need to add the
      following code to your app before calling any other Cloud Firestore methods:
      
        const firestore = new Firestore();
        const settings = {/* your settings... */ timestampsInSnapshots: true};
        firestore.settings(settings);
      
      With this change, timestamps stored in Cloud Firestore will be read back as
      Firebase Timestamp objects instead of as system Date objects. So you will also
      need to update code expecting a Date to instead expect a Timestamp. For example:
      
        // Old:
        const date = snapshot.get('created_at');
        // New:
        const timestamp = snapshot.get('created_at');
        const date = timestamp.toDate();
      
      Please audit all existing usages of Date when you enable the new behavior. In a
      future release, the behavior will change to the new behavior, so if you do not
      follow these steps, YOUR APP MAY BREAK.

There's no info about it neither in the documentation nor in the [`test.online.js`](https://github.com/firebase/functions-samples/blob/27c46763a774c8680165ae455b292661bb3890ef/quickstarts/uppercase/functions/test/test.online.js) document

**Comment by wujekbogdan** [comment]
I'm not really sure is it only the documentation issue. I tried to solve the problem as follows:

``` ts
import * as admin from "firebase-admin";
import * as FunctionsTest from "firebase-functions-test";
import "jest";
import * as path from "path";
import config from "../src/config";
import * as functions from "../src/index";

describe("test", () => {

  let functionsTest;

  beforeAll(() => {
    const configPath = path.resolve(__dirname, `../../env/serviceAccountKey.test.json`);

    admin.initializeApp({
      credential: admin.credential.cert(configPath),
      databaseURL: config("DATABASE_URL"),
      projectId: config("PROJECT_ID"),
    });

    admin.firestore().settings({
      timestampsInSnapshots: true,
    });

    functionsTest = FunctionsTest({
      databaseURL: config("DATABASE_URL"),
      projectId: config("PROJECT_ID"),
    }, configPath);
  });

  it("should do something...", () => {
    const snap = functionsTest.firestore.makeDocumentSnapshot({
      test: 2,
    }, "test-test/test");

    const wrapped = functionsTest.wrap(functions.setDashbordEntryTimestampOnCreate);

    wrapped(snap).then(() => {
      // Do something
    });
  });

});
```

but the notice doesn't go away. It happens only when executing unit tests after the `wrapped(snap)` function is executed. In "normal" application setting `timestampsInSnapshots` to `true` solves the problem.

**Comment by ampatspell** [comment]
For now there is a workaround to provide `{ app: admin.app }` as a third argument for `makeDocumentSnapshot`. Or monkeypatch functions test:

```
const admin = require('firebase-admin');
let app = admin.app();

const test = require('firebase-functions-test');
let instance = test(config.environment.test, config.serviceAccountKey);

let firestore = instance.firestore;
let fn = firestore.makeDocumentSnapshot;
firestore.makeDocumentSnapshot = (...args) => {
  return fn.call(firestore, ...args, { app });
};
```

**Comment by abehaskins** [comment]
You can fix this without the shim by @ampatspell by pulling the `firebase-function-test`'s `FirebaseApp` instance and changing the settings on that.

```js
import {testApp} from '../../src/app';
// This will only work with `online` tests, otherwise it will throw an error.
testApp().getApp().firestore().settings({
  timestampsInSnapshots: true,
});
```
