### ISSUE TITLE
snap.key is my wildcard

### ISSUE THREAD

**Issue by lukepighetti** [firebase/firebase-functions-test#26]
Given

```
functions.database
  .ref("/projects/{pid}")
  .onCreate(snap => {
    console.log(snap.key)
  }
```

When triggered with

```
const wrapped = fft.wrap(cloudFunctionUnderTest);

const path = "/projects/{pid}";

const options = {
  params: {
    pid: "project_id"
  }
};

const val = {test: "test"}

const snap = fft.database.makeDataSnapshot(val, path);

wrapped(snap, options);
```

Console.log() outputs
```
{pid}
```

**Comment by abehaskins** [comment]
Hi Luke!

This is expected (for now). The path provided to the snapshot is intended to be the full path of the snapshot, not the path the function is tied to. We don't make any modifications to the snapshot when we invoke the wrapped functions, the `options` object only influences the `context` passed as the second argument to `onCreate` and not the snapshot itself.

Feel free to do something like this to manually map your options `params` to your wildcard'ed path.

```js
const wrapped = fft.wrap(funcs.dbyay);

const path = "/projects/{pid}";

const options = {
    params: {
        pid: "project_id"
    }
};

const val = {test: "test"};

const snap = fft.database.makeDataSnapshot(val, Object.keys(options.params).reduce((s, k) => {
    return s.replace(`{${k}}`, options.params[k]);
}, path));

wrapped(snap, options);
```
