### ISSUE TITLE
Error: The default Firebase app does not exist. Make sure you call initializeApp() before using any of the Firebase services.

### ISSUE THREAD

**Issue by noor2096** [firebase/firebase-functions-test#46]
I am trying to create a Firebase Function but I am getting the following error:
![1](https://user-images.githubusercontent.com/52572667/63270408-8baecf00-c2b1-11e9-98cf-c32a1ed1a6a6.PNG)

This is my index.js file code
![2](https://user-images.githubusercontent.com/52572667/63270454-a1bc8f80-c2b1-11e9-9b75-2a7fc5d7be91.PNG)

I already tried different things but not getting any success.
Basically I want to send notifications from one device to other devices.
Kindly take a look and help me out. Thanks!

**Comment by laurenzlong** [comment]
Hi, this is not a bug with firebase-functions-test. If you need help writing a cloud function, please refer to our support channels: https://firebase.google.com/support
