### ISSUE TITLE
Error: The default Firebase app does not exist

### ISSUE THREAD

**Issue by btrautmann** [firebase/firebase-functions-test#6]
### Version info

**firebase-functions-test:** 0.1.1

**firebase-functions:** ^1.0.0

**firebase-admin:** ~5.11.0

### Test case

In **index.js** I have:

```
admin.initializeApp(functions.config().firebase);
```

Thus in **test.js** I have:
```
before(() => {
  // Trying to mock the config
  test.mockConfig({ firebase: 'FakeFirebaseConfig' });
  adminInitStub = sinon.stub(admin, 'initializeApp');
  myFunctions = require('../index');
});
```

### Steps to reproduce

Attempt to write a Firestore test that uses the above `before()` and uses `makeDocumentSnapshot()`, like:

```
  describe('updateActiveNotesCount', () => {
    // Test Case: Setting environments/{environment}/users/{userId}/people/{personId}/notes/{noteId}/isActive to 'true' should cause
    // .../{personId}/activeNotesCount to be incremented
    it('Should increment active notes count on the person field', () => {
      // Make snapshot for state of database beforehand
      const beforeSnap = test.firestore.makeDocumentSnapshot({isActive: false}, 'environments/dev/users/1/people/2/notes/3');
      // Make snapshot for state of database after the change
      const afterSnap = test.firestore.makeDocumentSnapshot({isActive: true}, 'environments/dev/users/1/people/2/notes/3');
      const change = test.makeChange(beforeSnap, afterSnap);
      // Call wrapped function with the Change object
      const wrapped = test.wrap(myFunctions.updateActiveNotesCount);
      wrapped(change);
      // Assert envinonments/dev/users/1 has `activeNotesCount` of 1
      return assert(true); // Not sure how to make this assertion yet, but doesn't matter
    })
  });
```

### Expected behavior

Test should run (and fail due to bad assertion) without any errors caused by SDK

### Actual behavior

`Error: The default Firebase app does not exist. Make sure you call initializeApp() before using any of the Firebase services.
      at FirebaseAppError.Error (native)
      at FirebaseAppError.FirebaseError [as constructor] (node_modules/firebase-admin/lib/utils/error.js:39:28)
      at FirebaseAppError.PrefixedFirebaseError [as constructor] (node_modules/firebase-admin/lib/utils/error.js:85:28)
      at new FirebaseAppError (node_modules/firebase-admin/lib/utils/error.js:119:28)
      at FirebaseNamespaceInternals.app (node_modules/firebase-admin/lib/firebase-namespace.js:105:19)
      at FirebaseNamespace.app (node_modules/firebase-admin/lib/firebase-namespace.js:372:30)
      at FirebaseNamespace.ensureApp (node_modules/firebase-admin/lib/firebase-namespace.js:388:24)
      at FirebaseNamespace.fn (node_modules/firebase-admin/lib/firebase-namespace.js:328:30)
      at Object.makeDocumentSnapshot (node_modules/firebase-functions-test/lib/providers/firestore.js:44:45)
      at Context.it (test/test.js:45:41)`

The relevant code within test.js at line 45 is:
```
const beforeSnap = test.firestore.makeDocumentSnapshot({isActive: false}, 'environments/dev/users/1/people/2/notes/3');
```

The relevant code within firestore.js at line 44 is:

```
else {
    firestoreService = firebase_admin_1.firestore(app_1.testApp().getApp()); // Line 44
    project = process.env.GCLOUD_PROJECT;
}
```

**Update:** I suspected that `firestore()` on `admin` needs to be mocked so I added:

```
firestoreStub = sinon.stub(admin, 'firestore');
```
but get the error:

```
TypeError: Attempted to wrap undefined property firestore as function
```

**Comment by abraham** [comment]
I'm having a similar issue.

**Comment by ahaverty** [comment]
The initializeApp call has changed from `admin.initializeApp(functions.config().firebase);` to this `admin.initializeApp();`
I'd start looking there if the error is related to initializeApp.
Their online docs go into detail on when to import certain things.

**Comment by btrautmann** [comment]
Interesting, thanks @ahaverty. Last I checked the config was still listed as the correct way to inject your env variables like Slack webhook URL, for instance (See [here](https://firebase.google.com/docs/functions/config-env)).

**Comment by ahaverty** [comment]
See: https://firebase.google.com/docs/functions/beta-v1-diff#functionsconfigfirebase_removed
 👍 
https://github.com/firebase/firebase-functions/issues/216 and https://github.com/firebase/firebase-functions/issues/220 are worth a read if you're still having issues

**Comment by btrautmann** [comment]
Thanks @ahaverty I'll check out the migration stuff and hopefully that resolves this issue!

**Comment by alvico** [comment]
Hitting the same wall >.<

**Comment by roykolak** [comment]
@alvico I solved my issue. I had my functions in separate files and each file did not include a call to `admin.initializeApp();` at the top. When I add a call to `admin.initializeApp();` at the top, my tests pass.

When I served my functions locally tho, it bombed out because an app can only be initialized once. Therefore, I updated the `initializeApp` line at the top of each of my function files to be this:

```
try {
  admin.initializeApp();
} catch (e) {}
```

**Comment by JFGHT** [comment]
@roykolak Hey, I'm facing exactly the same problem but I cannot fix it with your solution. Could you post your code somewhere? Thanks.

**Comment by nelsonlarocca** [comment]
> try {
>   admin.initializeApp();
> } catch (e) {}

is it the best / correct way to address that or just a fix in the meanwhile ?

**Comment by kirjai** [comment]
Here's an alternative fix that worked for me:
In the main file, which exports the functions, the order of imports matters
```
// index.ts file
import * as functions from 'firebase-functions';
import * as admin from 'firebase-admin';
admin.initializeApp(functions.config().firebase);

// the rest of my imports go here
import ...
```
That way, if any of the files that i'm importing *after* the app initialization rely on the default firebase app (like if they initialize the firestore for example), the default app should already be set.

I'm using Typescript though, so unsure whether this would work the same way in JS

**Comment by AnushangaWimalasena** [comment]
This might sound like crazy, But I had the same issue. Then I've changed my "admin.initializeApp();" place like below. Then it works.

//
const functions = require('firebase-functions');
const admin = require('firebase-admin');
const express = require('express');
const app = express();
//put here.
admin.initializeApp();


const db = admin.firestore();

const firebaseConfig = {
    // config data
         };


const firebase = require('firebase');

firebase.initializeApp(firebaseConfig);

**Comment by mahafuz** [comment]
> This might sound like crazy, But I had the same issue. Then I've changed my "admin.initializeApp();" place like below. Then it works.
> 
> //
> const functions = require('firebase-functions');
> const admin = require('firebase-admin');
> const express = require('express');
> const app = express();
> //put here.
> admin.initializeApp();
> 
> const db = admin.firestore();
> 
> const firebaseConfig = {
> // config data
> };
> 
> const firebase = require('firebase');
> 
> firebase.initializeApp(firebaseConfig);

It did work for me, Thank you <3

**Comment by relair** [comment]
I had the same issue as the OP. All the responses so far seem to be referring to completely different issues which have nothing to do with testing.
If someone finds this issue again the way to deal with it is to stub the get method:
```
firestoreStub = sinon.stub(admin, 'firestore')
  .get(function () {
    return function () {
      return "data";
    }
  });
```
It is also similar for other parts such as auth, so if you are going to use offline mode you need to make sure you mock everything.

**Comment by CharlieOxendine** [comment]
I am encountering the same problem and have tried everything above with no luck. At first I had issues with sinon, so I assumed it has something to do with having to stub out .initializeApp() in our test file. But even after getting that to work by manually installing npm sinon, I still received this error.

**Comment by NealEhardt** [comment]
Thank you @relair ! I was able to write offline unit tests without modifying the source file.

Here's my full firestore mock, which allows simple operations like `db.collection('dogs').doc('fido').get().exists` and `db.collection('dogs').doc('fido').set(...)`--

    docStub = sinon.stub().returns({
      get: () => ({
        exists: false
      }),
      set: sinon.stub()
    });
    firestoreStub = sinon.stub(admin, 'firestore')
      .get(() => (() => ({
        collection: () => ({
          doc: docStub
        })
      })));

**Comment by votala** [comment]
remove --only functions from package.json serve preset
