### ISSUE TITLE
Request: Pure Typescript implementation sample

### ISSUE THREAD

**Issue by ahaverty** [firebase/firebase-functions-test#8]
I'm struggling to get a pure typescript implementation working with this lib.
I've managed to get it working with requires and few type aliases to make it friendlier
e.g:
```typescript
const test: FeaturesList = require('firebase-functions-test')({
    databaseURL: `https://${projectId}.firebaseio.com`,
    storageBucket: `${projectId}.appspot.com`,
    projectId: projectId,
}, `./service-accounts/${projectId}-key.json`);

//..and in the after:
(test as any).cleanup();
```

Tying a pure typescript import doesn't seem to be initializing things properly _(errors about not-a-project.firebaseapp for example)_ and the definitions seem to be different than the samples _(the constructor wants a single parameter versus the two in the above sample and the js samples)_

Rather than raising an issue for everything I can't get to work, would it be possible to get a typescript sample? 🤓

**Comment by adamduren** [comment]
Just ran into this as well. Mainly the typings not accepting a second parameter for the service account for use in online mode.

**Comment by jeremylorino** [comment]
@ahaverty see if [this](https://github.com/jeremylorino/firebase-functions-unittest-cd/blob/master/functions/test/util.ts) helps.

I haven't updated the example repo with what I am currently using in my day-to-day:
```typescript
import { FeaturesList } from 'firebase-functions-test/lib/features';
import { FirebaseFunctionsTest } from 'firebase-functions-test/lib/lifecycle';

export declare type FirebaseFunctionsTestSuite =
  FirebaseFunctionsTest &
  { _cleanup: () => void; } &
  FeaturesList;

export async function getModelService() {
  const firebaseTestHarness: FirebaseFunctionsTestSuite = await require('firebase-functions-test')(projectConfig, process.env.GOOGLE_APPLICATION_CREDENTIALS);
  firebaseTestHarness._cleanup = firebaseTestHarness.cleanup;
  firebaseTestHarness.cleanup = function () {
    if (admin.apps.find(a => a.name === '[DEFAULT]')) {
      admin.app().delete();
    }
    // tslint:disable-next-line:no-invalid-this
    return this._cleanup();
  };

  return firebaseTestHarness;
}
```

**Comment by abehaskins** [comment]
Hey folks,

Sorry about the lack of response on this. It's definitely possible that the typings are incorrect or not idiomatic for Typescript (which would be funny since FFT is written in TS), however it's hard for me to know as of today what does / doesn't work since no specific sample is given and this issue is pretty old.

Could someone possibly give me a single failing Typescript test which I can work at? Otherwise I'm not sure where to start looking.

Thanks a ton!
abe

**Comment by abehaskins** [comment]
Following up, when testing the library in Typescript, it appears the biggest issue I see is the use of `export =` in our `index.ts` file which forces people to import into TS via `require` which is prone to breaking typings if you don't use the esoteric `import fft = require("firebase-functions-test")`, which is never shown in our examples.

If you import this way, then @jeremylorino's harness *should* be unnecessary. Can someone give this type of import a check in their use case and report back?

**Comment by eliotstock** [comment]
@abehaskins Thanks. This does indeed seem to work in my project without the test harness now.

`index.test.ts:`

```
import * as admin from 'firebase-admin';
import * as functions from 'firebase-functions';

const projectConfig = {
  projectId: 'my-project',
  databaseURL: 'https://my-projecty.firebaseio.com'
};
const test = require('firebase-functions-test')(projectConfig, './my-project-key.json');

export * from './some.test';
export * from './another.test';
```

**Comment by mayurdhurpate** [comment]
> Following up, when testing the library in Typescript, it appears the biggest issue I see is the use of `export =` in our `index.ts` file which forces people to import into TS via `require` which is prone to breaking typings if you don't use the esoteric `import fft = require("firebase-functions-test")`, which is never shown in our examples.

Using `import firebaseTest = require('firebase-functions-test')` works great for me! Recently created an integration test for a Cloud Firestore trigger. Typescript is able to understand and show all typings for _firebase-functions-test_ in VSCode.

Here is how I implemented it in Typescript and Jest:

**Initialization**
```
import * as admin from 'firebase-admin';
import {mockConfigData} from 'mockConfigData';
import * as path from "path";
import firebaseTest = require('firebase-functions-test'); 

const firebaseConfig = {
  databaseURL: 'https://project-id.firebaseio.com',
  storageBucket: 'project-id.appspot.com',
  projectId: 'project-id',
};
const testEnv = firebaseTest(firebaseConfig, path.resolve('service-key.json'));
testEnv.mockConfig(mockConfigData);  //optional
```

**Integration Test**

```
const myFunctions = require('../index.ts');   // relative path to functions code
const user_doc_data = { name: 'Mayur Dhurpate' };

describe('onUserCreate',()=>{
  beforeAll(async ()=>{
    await admin.firestore().collection('user_data').doc('1').set(user_doc_data);
  });

  it('creates correct firstname', async () => { 
    const snap = testEnv.firestore.makeDocumentSnapshot(user_doc_data, 'user_data/1');
    const wrapped = testEnv.wrap(myFunctions.onUserCreate);    // onUserCreate creates a new field firstName
    await wrapped(snap);
    const createdSnap = await admin.firestore().collection('user_data').doc('1').get();
    console.log(createdSnap.data());
    return expect(createdSnap.data()!.firstName).toBe('Mayur');
  });

  afterAll(async ()=>{
    await admin.firestore().collection('user_data').doc('1').delete(); 
  })
});
```

The only issue I faced is importing Functions code using `const myFunctions = require('../index.ts')` gets `myFunctions` as `any` type, maybe because of the way the Firebase Functions triggers are written. Would be great if we can add a Typescript implementation sample to the docs aiding the ones added for [Firebase Functions](https://github.com/firebase/functions-samples/tree/master/typescript-getting-started).

**Comment by jaonoctus** [comment]
And what about tests with Typescript HTTPS Functions using express app? How can we test it?

**Initialization example**
```ts
import { https } from 'firebase-functions'
import * as express from 'express'
import * as cors from 'cors'

const app = express()

app.use(cors({ origin: true }))

const verifyBodyMiddleware = (
  req: express.Request,
  res: express.Response,
  next: express.NextFunction
) => {
  if (!req.body.someRequiredField) next('undefined-field')

  next()
}

const helloWorldPostHandler = (
  req: express.Request,
  res: express.Response
) => {
  // at this point, we know that the body contains required fields
  const { someRequiredField } = req.body

  res.json({ data: { someRequiredField } })
}

const defaultErrorHandler = (
  err: any,
  req: express.Request,
  res: express.Response,
  next: express.NextFunction
) => {
  if (err === 'undefined-field') {
    // some handler for this error here
  }

  res.status(500).json({ error: 'error message' })
}

app.post('/', [
  verifyBodyMiddleware,
  helloWorldPostHandler,
  defaultErrorHandler
])

export const helloWorld = https.onRequest(app)

```

**Comment by Andrew-Pynch** [comment]
Can we please get an in-depth exploration of typescript + firebase-functions-test in online mode? I really don't understand how to get this working from the limited docs on firebase-functions-test or typescript support for firebase :-(

**Comment by doublethefish** [comment]
This thread appears to be outdated as this exists now (linked from [here](https://github.com/firebase/firebase-functions-test)):
https://github.com/firebase/functions-samples/tree/main/2nd-gen/test-functions-jest-ts/functions

**Comment by TheIronDev** [comment]
Thank you for calling that out! I'm going to continue updating `firebase-functions-test`, which includes better documentation and more samples. Please open up new issues to call out pain points that can be improved.

Thank you! 😄

**Comment by ChrisChiasson** [comment]
There are problems with the example linked above from doublethefish, so I don't think this should be closed. For example, its package.json contains two different versions of firebase-functions, one at version 3, one at version 4.

There don't appear to be any gen 1 examples of testing with typescript...

Finally, when cloning the repo and actually trying to run that test, it fails. Before getting to this point I globally installed pnpm, jest, mocha, ts-jest, etc (responding to various errors I saw).

```
chrischiasson@penguin:~/care/tmp/functions-samples/2nd-gen/test-functions-jest$ npm test

> functions-samples@1.0.0 test
> pnpm -r --workspace-concurrency=4 --aggregate-output run test

2nd-gen/alerts-to-discord/functions      |  WARN  Unsupported engine: wanted: {"node":"16"} (current: {"node":"v18.13.0","pnpm":"7.26.2"})
.../auth-blocking-functions/functions    |  WARN  Unsupported engine: wanted: {"node":"16"} (current: {"node":"v18.13.0","pnpm":"7.26.2"})
2nd-gen/callable-functions/functions     |  WARN  Unsupported engine: wanted: {"node":"16"} (current: {"node":"v18.13.0","pnpm":"7.26.2"})
2nd-gen/custom-events/functions          |  WARN  Unsupported engine: wanted: {"node":"16"} (current: {"node":"v18.13.0","pnpm":"7.26.2"})
.../functions                            |  WARN  Unsupported engine: wanted: {"node":"16"} (current: {"node":"v18.13.0","pnpm":"7.26.2"})
 WARN  59 other warnings
Scope: 64 of 65 workspace projects
2nd-gen/test-functions-jest-ts/functions test$ jest
│ ● Validation Error:
│   Preset ts-jest not found.
│   Configuration Documentation:
│   https://jestjs.io/docs/configuration
└─ Failed in 271ms at /home/chrischiasson/care/tmp/functions-samples/2nd-gen/test-functions-jest-ts/functions
quickstarts/uppercase/functions test$ npm run test-offline
└─ Running...
2nd-gen/test-functions-mocha/functions test$ mocha *.test.js
└─ Running...
2nd-gen/test-functions-jest/functions test$ jest
└─ Running...
/home/chrischiasson/care/tmp/functions-samples/2nd-gen/test-functions-jest-ts/functions:
 ERR_PNPM_RECURSIVE_RUN_FIRST_FAIL  test-functions@ test: `jest`
Exit status 1
```

**Comment by ChrisChiasson** [comment]
In my own work, I am hitting errors in the gen 1 wrap function saying that all overloads are invalid (after either doing import = require or enabling es6 module compatibility.

**Comment by ChrisChiasson** [comment]
I do notice this on the npm page of firebase functions test: "NOTE: This library can only be used with firebase-functions v3.20.1 or above." Maybe they are being sneaky and "letting us know" that it doesn't work with functions defined in firebase-functions version 4, especially those using `import {https} from "firebase-functions/v1"`.

**Comment by doublethefish** [comment]
You mention gen-1. Did you see the other link I added where multiple example projects are posted:
https://github.com/firebase/firebase-functions-test

ps. yep there are issues with the 2nd-gen project - they must not have stopped me from getting it working for some reason.

**Comment by ChrisChiasson** [comment]
As far as I can tell, the other testing samples (at least for jest) are not typescript (?)

**Comment by doublethefish** [comment]
IIRC that’s because there aren’t typescript defs for those versions of the module.

**Comment by doublethefish** [comment]
You should have a look.

**Comment by ChrisChiasson** [comment]
If we read this above from 2019 and accept it as true:
https://github.com/firebase/firebase-functions-test/issues/8#issuecomment-486670662

Then at least at that time gen 1 testing in a typescript environment was compiling. I do note that the function trigger type at that time was any. Maybe today the triggers and / or the wrap command have types now. I will try to cast to any or one of the other argument types and see if that works. Maybe they unintentionally broke it by adding more type info.

**Comment by ChrisChiasson** [comment]
It turns out that is the answer (see [previous post](https://github.com/firebase/firebase-functions-test/issues/8#issuecomment-1411796117)). **If you cast away the type of the V1 function passed to wrap, it will begin compiling the code.** Later on I hit an error and I saw that their V1 wrapping code in the package is already compiled down to javascript.


```
/// Example of the code inside firebase-functions-test/lib/v1.js
const lodash_1 = require("lodash");
const firebase_functions_1 = require("firebase-functions");
const helpers_1 = require("./cloudevent/mocks/helpers");
function wrapV1(cloudFunction) {
    if (!(0, lodash_1.has)(cloudFunction, '__endpoint')) {
        throw new Error('Wrap can only be called on functions written with the firebase-functions SDK.');
    }
    if ((0, lodash_1.has)(cloudFunction, '__endpoint.scheduleTrigger')) {
        const scheduledWrapped = (options) => {
            // Although in Typescript we require `options` some of our JS samples do not pass it.
            options = options || {};
            _checkOptionValidity(['eventId', 'timestamp'], options);
            const defaultContext = _makeDefaultContext(cloudFunction, options);
            const context = (0, lodash_1.merge)({}, defaultContext, options);
            // @ts-ignore
            return cloudFunction.run(context);
        };
        return scheduledWrapped;
    }
    if ((0, lodash_1.has)(cloudFunction, '__endpoint.httpsTrigger')) {
        throw new Error('Wrap function is only available for `onCall` HTTP functions, not `onRequest`.');
    }
    if (!(0, lodash_1.has)(cloudFunction, 'run')) {
        throw new Error('This library can only be used with functions written with firebase-functions v1.0.0 and above');
    }
    const isCallableFunction = (0, lodash_1.has)(cloudFunction, '__endpoint.callableTrigger');
```
