### ISSUE TITLE
let Syntax from "Intermediate Topics in Firebase" not valid

### ISSUE THREAD

**Issue by b0ot** [firebase/firebase-functions-test#83]
@samtstern

### Version info

**firebase-functions-test:**

**firebase-functions:**

**firebase-admin:**

firebase -V: 8.17.0

### Test case

Based on Firebase YouTube Tutorial: [Intermediate topics in Firebase Security Rules - Firecasts](https://youtu.be/8Mzb9zmnbJs?t=1143)

### Steps to reproduce

Todd has just refactored his code from:

```
      function postHasAllRequiredFields() {
        return (request.resource.data.keys().hasAll(["authorId", "visibility", "content", "headline"]));
      }
```
```
      function postHasAllRequiredFields() {
          let requiredFields = ["authorId", "visibility", "content", "headline"];
        return (request.resource.data.keys().hasAll(requiredFields));
      }
```

### Expected behavior

Refactored code should still pass test cases

### Actual behavior

```
npm test 
````
results in multiple errors:
```
Error: Expected PERMISSION_DENIED but got unexpected error: FirebaseError: [code=invalid-argument]: 3 INVALID_ARGUMENT: Error compiling rules:
L33:9 missing ';' at 'return'
```

The same result happens in the next section as well when Todd does the posthasonlyAllowedFields.

It appears that the "let" syntax is not valid.

**Comment by samtstern** [comment]
@b0ot I was not able to reproduce this.  Here's what I have:

**firestore.rules**
```
rules_version = '2'
service cloud.firestore {
  match /databases/{database}/documents {
    function postHasAllRequiredFields() {
      let requiredFields = ["authorId", "visibility", "content", "headline"];
      return (request.resource.data.keys().hasAll(requiredFields));
    }

    match /posts/{post} {
      allow read, write: if postHasAllRequiredFields();
    }
  }
}
```

***index.test.js***
```js
const firebase = require("@firebase/rules-unit-testing");

const app =firebase.initializeTestApp({
  projectId: "fir-dumpster"
});

const db = app.firestore();

async function main() {
  await firebase.assertSucceeds(db.collection('posts').add({
    "authorId": "foo",
    "visibility": "bar",
    "content": "baz",
    "headline": "qux",
  }));
  console.log("Request succeeded.");
  
  await firebase.assertFails(db.collection('posts').add({
    "authorId": "foo",
    "visibility": "bar",
    "content": "baz",
  }));
  console.log("Request failed.");
}

main();
```

Then here's what I get when I run it:
```
$ firebase emulators:exec "node index.test.js"
i  emulators: Starting emulators: firestore
i  firestore: Firestore Emulator logging to firestore-debug.log
i  Running script: node index.test.js
Request succeeded.
Request failed.
✔  Script exited successfully (code 0)
i  emulators: Shutting down emulators.
i  firestore: Stopping Firestore Emulator
i  hub: Stopping emulator hub
```

I think you must have a syntax error in your rules somewhere?

**Comment by b0ot** [comment]
Sam,
If there is a syntax error, I haven't been able to figure it out.
I will confirm that I am able to use let within functions at the
match /databases/{database}/documents {
level.

I tried to simplify the testing further and created the following.

**This works for 100% of test cases**
```
      function postHasOnlyAllowedFields() {
        return request.resource.data.keys().hasOnly(["authorId", "visibility", "content", "headline", "photo", "tags", "location"])
      }

      // function postHasOnlyAllowedFields() {
      //   let requiredAndOptionalFields = ["authorId", "visibility", "content", "headline", "photo", "tags", "location"]
      //   return request.resource.data.keys().hasOnly(requiredAndOptionalFields);
      // }
```

**This does NOT work**
```
      // function postHasOnlyAllowedFields() {
      //   return request.resource.data.keys().hasOnly(["authorId", "visibility", "content", "headline", "photo", "tags", "location"])
      // }

      function postHasOnlyAllowedFields() {
        let requiredAndOptionalFields = ["authorId", "visibility", "content", "headline", "photo", "tags", "location"]
        return request.resource.data.keys().hasOnly(requiredAndOptionalFields);
      }
```

The error is: 
```
     Error: 3 INVALID_ARGUMENT: Error compiling rules:
L48:9 missing ';' at 'return'
```
L48 refers to:  
return request.resource.data.keys().hasOnly(requiredAndOptionalFields);

**Comment by b0ot** [comment]
Ok, I'm an idiot... the error and Line Number had me so focused on the return statement, however it was actually the line above that had the issue.

I simply needed to add a ';' to the end of:
let requiredAndOptionalFields = ["authorId", "visibility", "content", "headline", "photo", "tags", "location"];

**Comment by samtstern** [comment]
@b0ot thank you for following up and glad you fixed it!  I think your earlier frustrations make it perfectly reasonable that you suspect a bug, you have definitely encountered some real ones before.

**Comment by vdiaz1130** [comment]
Importing clearFirestoreData from '@firebase/rules-unit-testing'; no longer works with version 2.0.0. How do we import it now? 

![image](https://user-images.githubusercontent.com/24530571/133725715-7f22411c-0ee6-4433-ba17-ea371c7060f1.png)
