### ISSUE TITLE
Running unit tests ends with error message "The 'credential' property must be an object which implements the Credential interface" even the GOOGLE_APPLICATION_CREDENTIALS env var is set

### ISSUE THREAD

**Issue by shunei4517** [firebase/firebase-functions-test#92]
### Version info

**firebase-functions-test:**
0.2.3
**firebase-functions:**
3.13.2
**firebase-admin:**
9.5.0
### Test case
- target code
  - this functions is almost same with `makeUppercase` function introduced in [official firebase guide](https://firebase.google.com/docs/functions/get-started#add-the-makeuppercase-function)
```typescript
import { region as functionBuilder } from 'firebase-functions';
import { initializeApp, credential } from 'firebase-admin';

initializeApp({
  credential: credential.applicationDefault(),
});

export const makeUppercase = functionBuilder('asia-northeast1')
  .firestore.document('/messages/{documentId}')
  .onCreate(async (snapshot) => {
    const original = snapshot.data().original as string;
    const uppercase = original.toUpperCase();
    await snapshot.ref.set({ uppercase }, { merge: true });
  });
```
- unit test
  - this test checks whether the upper case message is added or not on firestore after cloud function is executed
```typescript
import test from 'firebase-functions-test';
import { firestore } from 'firebase-admin';
import { credential } from 'firebase-admin';

import { makeUppercase } from '../src/index';

const tester = test({
  credential: credential.applicationDefault(),
});

it('Tests the sample makeUppercase function', async (done) => {
  const db = firestore();

  const path = 'messages/data1';

  const original = 'original';
  const uppercase = original.toUpperCase();

  afterEach(async () => {
    tester.cleanup();
    await db.doc(path).delete();
  });

  const wrapped = tester.wrap(makeUppercase);
  const snapshot = tester.firestore.makeDocumentSnapshot(
    {
      original,
    },
    path
  );

  db.doc(path).onSnapshot(
    (snapshot) => {
      const data = snapshot.data();
      const result = data?.uppercase;
      if (result == undefined) {
        return;
      }
      expect(result).toEqual(uppercase);
    },
    (error) => {
      done(error);
    }
  );
  await wrapped(snapshot);
});
```

### Steps to reproduce

Clone [this repo](https://github.com/shunei4517/cloud-functions-for-firebase-starter) and follow these steps

- create the new firebase project and get the service account key by following [this guide](https://cloud.google.com/docs/authentication/production#manually)
- store the service account key to `functions/service-account-key.json`
- prepare docker container
```zsh
docker build .
docker run -it --mount type=bind,src=$PWD,dst=/app YOUR_IMAGE_ID
```
- install dependencies
```zsh
yarn install
```
- run unit test
```zsh
yarn test
```
### Expected behavior

- `firebase-functions-test` is able to read the credential from `credential.applicationDefault()`

### Actual behavior

- Unit test ends with error message below
```
Invalid Firebase app options passed as the first argument to initializeApp() for the app named "firebase-functions-test". The "credential" property must be an object which implements the Credential interface.
```

**Comment by louis030195** [comment]
Same issue, only happen when trying to use `makeDocumentSnapshot`yet

**Comment by Yoshihide-Nishimoto** [comment]
Same here

**Comment by inlined** [comment]
On one hand, I think I see a bug, but on the other, this code sample doesn't follow the SDK's instructions. If you're going to use a credentials file, you should pass that value as the second parameter to initialize your tests:

```
const tester = test({}, process.env.GOOGLE_APPLICATION_CREDENTIALS);
```
