### ISSUE TITLE
Type of makeDocumentSnapshot does not accept null value. 

### ISSUE THREAD

**Issue by kub1x** [firebase/firebase-functions-test#94]
### Version info

**firebase-functions-test:0.2.3**

**firebase-functions:3.13.2**

**firebase-admin:9.5.0**

### Test case

```js
import * as myFunctions from '../src';
const wrapped = test.wrap(myFunctions.someFunction);

const data_path = 'myCollectionName/myDocId';
const beforeSnap = test.firestore.makeDocumentSnapshot(null, data_path); // <-- Rises a Typescript error
const afterSnap = test.firestore.makeDocumentSnapshot({ myprop: 'After Value' }, data_path);
const change = test.makeChange(beforeSnap, afterSnap);

await wrapped(change);
```

### Steps to reproduce

The `makeDocumentSnapshot` with null as first parameter. 

### Expected behavior

Expect the `makeDocumentSnapshot` typescript type to allow me to pass null as first argument. 

I'd expect the function to create document snapshot with `exists` set to false. Otherwise testing document creation/deletion with `onWrite` event handler won't be possible (like in [this example](https://github.com/EvsWorld/test2/blob/8798251316afa12f2ce99343cd7e4b97d8989c86/functions/src/indexUser/indexUser.spec.js#L65)). 

### Actual behavior

Calling the `makeDocumentSnapshot` with null rises typescript error: 
```
Argument of type 'null' is not assignable to parameter of type '{ [key: string]: any; }'.
const beforeSnap = test.firestore.makeDocumentSnapshot(null, data_path);
```

**Comment by kub1x** [comment]
Found in [other repo](https://github.com/Hacksie/bullt.io/blob/b47522910c9f023395cc190a0234f71777f3d95e/functions/src/indexUser/indexUser.spec.ts#L39) that manually setting the first argument to `null as any` allows me to pass null there and the test works that way. 

As null seems to be a valid value of the argument, it probably should be allowed by the type definition. Current behavior feels misleading.

**Comment by wceolin** [comment]
Not sure if not accepting `null` is intentional or a bug but I noticed they [recommend](https://github.com/firebase/firebase-functions-test/blob/master/src/providers/firestore.ts#L48) passing `{}` to mock the snapshot a document that doesn't exist.

**Comment by taeold** [comment]
Thanks @wceolin for sharing your comment.

@kub1x is I think passing in an empty object is equivalent to what you want to achieve with passing in null. Is there something preventing you from doing that instead?

FWIW I don't know why `makeDocumentSnapshot` is designed this way, but I don't think it's a bug.

**Comment by kub1x** [comment]
Thanks, I've tested it and yes, it marks the empty object as `exists === false` too. A little counter intuitive, but works. 
I don't think I would have learned about this if I didn't ask here. Thanks!
